#RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Tencent/Tencent.list

DOMAIN-KEYWORD,tencent.com
DOMAIN-KEYWORD,accessibility-union
DOMAIN-KEYWORD,qcloud
DOMAIN-KEYWORD,tencentcloud
DOMAIN-KEYWORD,tencent
DOMAIN-KEYWORD,tliveweb
DOMAIN-KEYWORD,alipay

DOMAIN-SUFFIX,tencent-cloud.net
DOMAIN-SUFFIX,qcloud.com
DOMAIN-SUFFIX,aliyun-inc.com
DOMAIN-SUFFIX,qcly.xyz
DOMAIN-SUFFIX,qq.cn.com
DOMAIN-SUFFIX,qwebapp.com
DOMAIN-SUFFIX,qtslog.com
DOMAIN-SUFFIX,rootjl.com
DOMAIN-SUFFIX,qq.com.cn
DOMAIN-SUFFIX,qq.com
DOMAIN-SUFFIX,qlogo.cn
DOMAIN-SUFFIX,wechat.com
DOMAIN-SUFFIX,weixin.com
DOMAIN-SUFFIX,wechatpay.cn
DOMAIN-SUFFIX,wechatpay.com
DOMAIN-SUFFIX,xy-asia.com
DOMAIN-SUFFIX,gtimg.com
DOMAIN-SUFFIX,gservicewechat.com
DOMAIN-SUFFIX,tenpay.com
DOMAIN-SUFFIX,wechatlegal.net
DOMAIN-SUFFIX,wechatos.net
DOMAIN-SUFFIX,weixinbridge.com
DOMAIN-SUFFIX,weixinsxy.com

DOMAIN-SUFFIX,alipay.com
DOMAIN-SUFFIX,alipayobjects.com
DOMAIN-SUFFIX,aliapp.org
DOMAIN-SUFFIX,alicdn.com
DOMAIN-SUFFIX,taobao.com
DOMAIN-SUFFIX,ucweb.com
DOMAIN-SUFFIX,ifaa.org.cn
DOMAIN-SUFFIX,sinopayment.com.cn
DOMAIN-SUFFIX,luohanacademy.com

USER-AGENT,MicroMessenger*
USER-AGENT,WeChat*
USER-AGENT,MOO%E9%9F%B3%E4%B9%90*
USER-AGENT,QQ%E9%9F%B3%E4%B9%90
USER-AGENT,TencentMidasConnect*
USER-AGENT,live4iphone*
USER-AGENT,qqlive4iphone*
USER-AGENT,AlipayClient*
IP-CIDR,101.32.104.4/32,no-resolve
IP-CIDR,101.32.104.41/32,no-resolve
IP-CIDR,101.32.104.56/32,no-resolve
IP-CIDR,101.32.118.25/32,no-resolve
IP-CIDR,101.32.133.16/32,no-resolve
IP-CIDR,101.32.133.209/32,no-resolve
IP-CIDR,101.32.133.53/32,no-resolve
IP-CIDR,103.238.16.0/23,no-resolve
IP-CIDR,103.7.28.0/22,no-resolve
IP-CIDR,119.147.8.78/32,no-resolve
IP-CIDR,120.41.44.0/32,no-resolve
IP-CIDR,122.5.0.129/32,no-resolve
IP-CIDR,129.226.107.244/32,no-resolve
IP-CIDR,129.226.3.47/32,no-resolve
IP-CIDR,140.249.239.0/32,no-resolve
IP-CIDR,140.249.28.0/32,no-resolve
IP-CIDR,150.138.137.0/32,no-resolve
IP-CIDR,150.139.143.0/32,no-resolve
IP-CIDR,27.159.95.0/32,no-resolve
IP-CIDR,58.58.81.129/32,no-resolve

IP-ASN,132203,no-resolve
