DOMAIN-KEYWORD,apple-support.akadns.net
DOMAIN-KEYWORD,xiaoping
DOMAIN-KEYWORD,-cn-,

DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,futunn.com
DOMAIN-SUFFIX,58.com
DOMAIN-SUFFIX,fang.com
DOMAIN-SUFFIX,soufanimg.com
DOMAIN-SUFFIX,cn
DOMAIN-SUFFIX,myeebus.com 
DOMAIN-SUFFIX,hkcsl.com
DOMAIN-SUFFIX,bytedance.com
DOMAIN-SUFFIX,douyin.com
DOMAIN-SUFFIX,douyinstatic.com
DOMAIN-SUFFIX,zijieapi.com
DOMAIN-SUFFIX,yhgfb-cn-static.com
DOMAIN-SUFFIX,bytetos.com
DOMAIN-SUFFIX,bytegoofy.com
DOMAIN-SUFFIX,byteimg.com
DOMAIN-SUFFIX,bytetcc.com
DOMAIN-SUFFIX,ibytedapm.com
DOMAIN-SUFFIX,zjcdn.com
DOMAIN-SUFFIX,douyinpic.com

USER-AGENT,*FindMyiPhone?
IP-CIDR,205.180.175.0/24
